In [3]:
import os
import cv2
import numpy as np
from tqdm import tqdm
import torch

REBUILD_DATA = True

if torch.cuda.is_available():
    device = torch.device("cuda:0")  # you can continue going on here, like cuda:1 cuda:2....etc. 
    print("Running on the GPU")
else:
    device = torch.device("cpu")
    print("Running on the CPU")

class animals():
    IMG_SIZE = 50
    Cats = "data/Cat"
    Dogs = "data/Dog"
    Foxs = "data/Fox"
    training_Data = []
    Labels = {Cats : 0 , Dogs : 1,Foxs:2}
    counter = {Cats : 0 , Dogs : 0,Foxs:0}    
    
    def importData(self):
        for label in self.Labels:
            for f in tqdm(os.listdir(label)):
                try:
                    path = os.path.join(label,f)
                    img = cv2.imread(path,
                                     cv2.IMREAD_GRAYSCALE)
                    img = cv2.resize(img,
                                     (self.IMG_SIZE,self.IMG_SIZE))
                    self.training_Data.append([np.array(img), 
                                               np.eye(3)[self.Labels[label]]])
                    if label == self.Cats:
                        counter["Cats"]+=1
                    elif label == self.Dogs:
                        counter["Dogs"]+=1
                    elif label == self.Foxs:
                        counter["Foxs"]+=1
                    
                except Exception as e :
                    pass
        
        np.random.shuffle(self.training_Data)
        np.save("training_Data.npy",self.training_Data)
                
            
if REBUILD_DATA:
    animal = animals()
    animal.importData()
    

  0%|▏                                                                             | 39/12502 [00:00<00:32, 384.22it/s]

Running on the GPU


100%|███████████████████████████████████████████████████████████████████████████████| 665/665 [00:05<00:00, 118.47it/s]
C:\Users\USER\Anaconda3\lib\site-packages\numpy\core\_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)


In [4]:
training_Data = np.load("training_Data.npy",allow_pickle=True)

In [5]:
len(training_Data)

25611

In [6]:
training_Data[0][1]

array([0., 1., 0.])

In [7]:
 
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        # Conv2d(input,features,size)
        self.conv1 = nn.Conv2d(1,32,5)
        self.conv2 = nn.Conv2d(32,64,5)
        self.conv3 = nn.Conv2d(64,128,5)
        self.fc1 = nn.Linear(51200,512)
        self.fc2 = nn.Linear(512,3)
    
    def convs(self,x):
        
        x =  F.max_pool2d(F.relu(self.conv1(x)),(2,2))
        x =  F.max_pool2d(F.relu(self.conv2(x)),(2,2))
        x =  F.max_pool2d(F.relu(self.conv3(x)),(2,2))
    
        return F.softmax(x,dim=1) 
    
    def forward(self,x):
        try : 
            x = self.convs(x)
            # flatten

            x = torch.flatten(x)
            
            self.fc1 = nn.Linear(x.size()[0],512)
            x = F.relu(self.fc1(x))
            x = self.fc2(x)
            return x
        except Exception as e:
            print(e)
            return e
        
net = Net()     

In [8]:
import torch.optim as optim

optimizer = optim.Adam(net.parameters(),lr=0.001)
loss_function = nn.MSELoss()

x = torch.Tensor([i[0] for i in training_Data]).view(-1,50,50)
x = x/255.0
y = torch.Tensor([i[1] for i in training_Data])
    
VAL_PCT = 0.1
val_size = int(len(x)*VAL_PCT)


In [9]:
train_x = x[:-val_size]
train_y = y[:-val_size]

test_x = x[-val_size:]
test_y = y[-val_size:]

In [10]:
BATCH_SIZE = 100
EPOCHS = 1

for epoch in range(EPOCHS):
    for i in tqdm(range(0,len(train_x),BATCH_SIZE)):
        try:
            batch_x = train_x[i:i+BATCH_SIZE].view(-1,1,50,50)
            batch_y = train_y[i:i+BATCH_SIZE]
            net.zero_grad()
            outputs = net.forward(batch_x)
            print(outputs)
            loss = loss_function(outputs,batch_y)
            loss.backward()
            optimizer.step()
        except Exception as e:
            pass
print(loss)

  0%|                                                                                          | 0/231 [00:00<?, ?it/s]

tensor([-0.0377,  0.0361,  0.0236], grad_fn=<AddBackward0>)


C:\Users\USER\Anaconda3\lib\site-packages\torch\nn\modules\loss.py:432: UserWarning: Using a target size (torch.Size([100, 3])) that is different to the input size (torch.Size([3])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
  0%|▎                                                                                 | 1/231 [00:00<02:27,  1.56it/s]

tensor([-0.0340,  0.0361,  0.0223], grad_fn=<AddBackward0>)


  1%|▋                                                                                 | 2/231 [00:01<02:22,  1.61it/s]

tensor([-0.0347,  0.0391,  0.0266], grad_fn=<AddBackward0>)


  1%|█                                                                                 | 3/231 [00:01<02:19,  1.63it/s]

tensor([-0.0328,  0.0420,  0.0265], grad_fn=<AddBackward0>)


  2%|█▍                                                                                | 4/231 [00:02<02:17,  1.66it/s]

tensor([-0.0290,  0.0424,  0.0231], grad_fn=<AddBackward0>)


  2%|█▊                                                                                | 5/231 [00:02<02:16,  1.65it/s]

tensor([-0.0284,  0.0445,  0.0284], grad_fn=<AddBackward0>)


  3%|██▏                                                                               | 6/231 [00:03<02:14,  1.67it/s]

tensor([-0.0286,  0.0450,  0.0256], grad_fn=<AddBackward0>)


  3%|██▍                                                                               | 7/231 [00:04<02:13,  1.68it/s]

tensor([-0.0237,  0.0487,  0.0250], grad_fn=<AddBackward0>)


  3%|██▊                                                                               | 8/231 [00:04<02:12,  1.69it/s]

tensor([-0.0242,  0.0490,  0.0273], grad_fn=<AddBackward0>)


  4%|███▏                                                                              | 9/231 [00:05<02:10,  1.70it/s]

tensor([-0.0209,  0.0489,  0.0302], grad_fn=<AddBackward0>)


  4%|███▌                                                                             | 10/231 [00:05<02:09,  1.71it/s]

tensor([-0.0176,  0.0561,  0.0324], grad_fn=<AddBackward0>)


  5%|███▊                                                                             | 11/231 [00:06<02:08,  1.71it/s]

tensor([-0.0108,  0.0579,  0.0236], grad_fn=<AddBackward0>)


  5%|████▏                                                                            | 12/231 [00:07<02:07,  1.72it/s]

tensor([-0.0032,  0.0614,  0.0262], grad_fn=<AddBackward0>)


  6%|████▌                                                                            | 13/231 [00:07<02:07,  1.71it/s]

tensor([0.0031, 0.0833, 0.0226], grad_fn=<AddBackward0>)


  6%|████▉                                                                            | 14/231 [00:08<02:06,  1.72it/s]

tensor([0.0409, 0.1166, 0.0179], grad_fn=<AddBackward0>)


  6%|█████▎                                                                           | 15/231 [00:08<02:05,  1.72it/s]

tensor([0.0607, 0.1430, 0.0425], grad_fn=<AddBackward0>)


  7%|█████▌                                                                           | 16/231 [00:09<02:06,  1.71it/s]

tensor([0.0754, 0.1640, 0.0505], grad_fn=<AddBackward0>)


  7%|█████▉                                                                           | 17/231 [00:09<02:04,  1.72it/s]

tensor([0.0716, 0.1858, 0.0520], grad_fn=<AddBackward0>)


  8%|██████▎                                                                          | 18/231 [00:10<02:03,  1.73it/s]

tensor([0.0871, 0.1718, 0.0353], grad_fn=<AddBackward0>)


  8%|██████▋                                                                          | 19/231 [00:11<02:02,  1.73it/s]

tensor([0.0984, 0.1672, 0.0597], grad_fn=<AddBackward0>)


  9%|███████                                                                          | 20/231 [00:11<02:02,  1.72it/s]

tensor([0.1317, 0.1966, 0.0476], grad_fn=<AddBackward0>)


  9%|███████▎                                                                         | 21/231 [00:12<02:02,  1.71it/s]

tensor([0.0985, 0.1837, 0.0170], grad_fn=<AddBackward0>)


 10%|███████▋                                                                         | 22/231 [00:12<02:01,  1.71it/s]

tensor([0.1169, 0.1945, 0.0315], grad_fn=<AddBackward0>)


 10%|████████                                                                         | 23/231 [00:13<02:02,  1.70it/s]

tensor([0.1331, 0.2563, 0.0372], grad_fn=<AddBackward0>)


 10%|████████▍                                                                        | 24/231 [00:14<02:00,  1.71it/s]

tensor([0.1487, 0.2196, 0.0335], grad_fn=<AddBackward0>)


 11%|████████▊                                                                        | 25/231 [00:14<01:59,  1.72it/s]

tensor([0.1346, 0.2160, 0.0364], grad_fn=<AddBackward0>)


 11%|█████████                                                                        | 26/231 [00:15<01:59,  1.72it/s]

tensor([0.1600, 0.2090, 0.0392], grad_fn=<AddBackward0>)


 12%|█████████▍                                                                       | 27/231 [00:15<01:58,  1.72it/s]

tensor([0.1679, 0.2415, 0.0236], grad_fn=<AddBackward0>)


 12%|█████████▊                                                                       | 28/231 [00:16<01:58,  1.72it/s]

tensor([0.1937, 0.2566, 0.0269], grad_fn=<AddBackward0>)


 13%|██████████▏                                                                      | 29/231 [00:16<01:58,  1.71it/s]

tensor([0.1588, 0.2549, 0.0231], grad_fn=<AddBackward0>)


 13%|██████████▌                                                                      | 30/231 [00:17<01:58,  1.70it/s]

tensor([0.1874, 0.2806, 0.0076], grad_fn=<AddBackward0>)


 13%|██████████▊                                                                      | 31/231 [00:18<01:57,  1.70it/s]

tensor([0.2112, 0.2523, 0.0051], grad_fn=<AddBackward0>)


 14%|███████████▏                                                                     | 32/231 [00:18<01:56,  1.70it/s]

tensor([0.2033, 0.3128, 0.0128], grad_fn=<AddBackward0>)


 14%|███████████▌                                                                     | 33/231 [00:19<01:56,  1.69it/s]

tensor([0.1986, 0.2892, 0.0274], grad_fn=<AddBackward0>)


 15%|███████████▉                                                                     | 34/231 [00:19<01:55,  1.70it/s]

tensor([0.2334, 0.3268, 0.0316], grad_fn=<AddBackward0>)


 15%|████████████▎                                                                    | 35/231 [00:20<01:55,  1.70it/s]

tensor([0.1968, 0.2691, 0.0434], grad_fn=<AddBackward0>)


 16%|████████████▌                                                                    | 36/231 [00:21<01:55,  1.69it/s]

tensor([0.2223, 0.3001, 0.0366], grad_fn=<AddBackward0>)


 16%|████████████▉                                                                    | 37/231 [00:21<01:53,  1.71it/s]

tensor([0.2486, 0.3439, 0.0434], grad_fn=<AddBackward0>)


 16%|█████████████▎                                                                   | 38/231 [00:22<01:52,  1.71it/s]

tensor([0.2250, 0.2870, 0.0419], grad_fn=<AddBackward0>)


 17%|█████████████▋                                                                   | 39/231 [00:22<01:53,  1.70it/s]

tensor([0.2629, 0.3144, 0.0031], grad_fn=<AddBackward0>)


 17%|██████████████                                                                   | 40/231 [00:23<01:52,  1.70it/s]

tensor([0.2891, 0.3496, 0.0426], grad_fn=<AddBackward0>)


 18%|██████████████▍                                                                  | 41/231 [00:24<01:51,  1.71it/s]

tensor([0.2742, 0.3260, 0.0415], grad_fn=<AddBackward0>)


 18%|██████████████▋                                                                  | 42/231 [00:24<01:50,  1.71it/s]

tensor([0.2528, 0.3028, 0.0420], grad_fn=<AddBackward0>)


 19%|███████████████                                                                  | 43/231 [00:25<01:50,  1.71it/s]

tensor([0.2882, 0.3647, 0.0504], grad_fn=<AddBackward0>)


 19%|███████████████▍                                                                 | 44/231 [00:25<01:49,  1.71it/s]

tensor([0.2541, 0.3126, 0.0311], grad_fn=<AddBackward0>)


 19%|███████████████▊                                                                 | 45/231 [00:26<01:49,  1.70it/s]

tensor([0.2772, 0.3604, 0.0334], grad_fn=<AddBackward0>)


 20%|████████████████▏                                                                | 46/231 [00:26<01:49,  1.69it/s]

tensor([0.2822, 0.3676, 0.0147], grad_fn=<AddBackward0>)


 20%|████████████████▍                                                                | 47/231 [00:27<01:49,  1.67it/s]

tensor([0.3124, 0.4057, 0.0213], grad_fn=<AddBackward0>)


 21%|████████████████▊                                                                | 48/231 [00:28<01:49,  1.67it/s]

tensor([0.2963, 0.3499, 0.0265], grad_fn=<AddBackward0>)


 21%|█████████████████▏                                                               | 49/231 [00:28<01:48,  1.67it/s]

tensor([0.3241, 0.4021, 0.0362], grad_fn=<AddBackward0>)


 22%|█████████████████▌                                                               | 50/231 [00:29<01:49,  1.66it/s]

tensor([0.2906, 0.3776, 0.0106], grad_fn=<AddBackward0>)


 22%|█████████████████▉                                                               | 51/231 [00:30<01:48,  1.66it/s]

tensor([0.2868, 0.3846, 0.0365], grad_fn=<AddBackward0>)


 23%|██████████████████▏                                                              | 52/231 [00:30<01:47,  1.66it/s]

tensor([0.3416, 0.3836, 0.0200], grad_fn=<AddBackward0>)


 23%|██████████████████▌                                                              | 53/231 [00:31<01:46,  1.67it/s]

tensor([0.3460, 0.4849, 0.0054], grad_fn=<AddBackward0>)


 23%|██████████████████▉                                                              | 54/231 [00:31<01:46,  1.67it/s]

tensor([0.3487, 0.4258, 0.0228], grad_fn=<AddBackward0>)


 24%|███████████████████▎                                                             | 55/231 [00:32<01:46,  1.65it/s]

tensor([0.3075, 0.3815, 0.0459], grad_fn=<AddBackward0>)


 24%|███████████████████▋                                                             | 56/231 [00:33<01:45,  1.66it/s]

tensor([0.3823, 0.4247, 0.0067], grad_fn=<AddBackward0>)


 25%|███████████████████▉                                                             | 57/231 [00:33<01:45,  1.65it/s]

tensor([0.3545, 0.4198, 0.0264], grad_fn=<AddBackward0>)


 25%|████████████████████▎                                                            | 58/231 [00:34<01:43,  1.67it/s]

tensor([0.3386, 0.4067, 0.0065], grad_fn=<AddBackward0>)


 26%|████████████████████▋                                                            | 59/231 [00:34<01:43,  1.66it/s]

tensor([0.3704, 0.4613, 0.0125], grad_fn=<AddBackward0>)


 26%|█████████████████████                                                            | 60/231 [00:35<01:43,  1.65it/s]

tensor([0.3967, 0.4834, 0.0177], grad_fn=<AddBackward0>)


 26%|█████████████████████▍                                                           | 61/231 [00:36<01:44,  1.63it/s]

tensor([0.3214, 0.4033, 0.0310], grad_fn=<AddBackward0>)


 27%|█████████████████████▋                                                           | 62/231 [00:36<01:42,  1.64it/s]

tensor([0.4150, 0.4304, 0.0341], grad_fn=<AddBackward0>)


 27%|██████████████████████                                                           | 63/231 [00:37<01:42,  1.64it/s]

tensor([0.3407, 0.4233, 0.0060], grad_fn=<AddBackward0>)


 28%|██████████████████████▍                                                          | 64/231 [00:37<01:40,  1.65it/s]

tensor([0.3536, 0.4464, 0.0348], grad_fn=<AddBackward0>)


 28%|██████████████████████▊                                                          | 65/231 [00:38<01:41,  1.64it/s]

tensor([0.3673, 0.4207, 0.0165], grad_fn=<AddBackward0>)


 29%|███████████████████████▏                                                         | 66/231 [00:39<01:41,  1.63it/s]

tensor([0.4561, 0.4977, 0.0431], grad_fn=<AddBackward0>)


 29%|███████████████████████▍                                                         | 67/231 [00:39<01:41,  1.62it/s]

tensor([0.3862, 0.3933, 0.0265], grad_fn=<AddBackward0>)


 29%|███████████████████████▊                                                         | 68/231 [00:40<01:40,  1.62it/s]

tensor([0.4257, 0.4669, 0.0260], grad_fn=<AddBackward0>)


 30%|████████████████████████▏                                                        | 69/231 [00:40<01:39,  1.63it/s]

tensor([0.3890, 0.4672, 0.0348], grad_fn=<AddBackward0>)


 30%|████████████████████████▌                                                        | 70/231 [00:41<01:37,  1.64it/s]

tensor([0.4491, 0.5109, 0.0256], grad_fn=<AddBackward0>)


 31%|████████████████████████▉                                                        | 71/231 [00:42<01:38,  1.62it/s]

tensor([ 0.4445,  0.4881, -0.0057], grad_fn=<AddBackward0>)


 31%|█████████████████████████▏                                                       | 72/231 [00:42<01:38,  1.61it/s]

tensor([0.4107, 0.4236, 0.0044], grad_fn=<AddBackward0>)


 32%|█████████████████████████▌                                                       | 73/231 [00:43<01:37,  1.62it/s]

tensor([0.4772, 0.4768, 0.0300], grad_fn=<AddBackward0>)


 32%|█████████████████████████▉                                                       | 74/231 [00:44<01:36,  1.62it/s]

tensor([0.3851, 0.4255, 0.0263], grad_fn=<AddBackward0>)


 32%|██████████████████████████▎                                                      | 75/231 [00:44<01:37,  1.59it/s]

tensor([0.4679, 0.4716, 0.0533], grad_fn=<AddBackward0>)


 33%|██████████████████████████▋                                                      | 76/231 [00:45<01:38,  1.58it/s]

tensor([0.4446, 0.4977, 0.0634], grad_fn=<AddBackward0>)


 33%|███████████████████████████                                                      | 77/231 [00:46<01:38,  1.57it/s]

tensor([0.4242, 0.4776, 0.0006], grad_fn=<AddBackward0>)


 34%|███████████████████████████▎                                                     | 78/231 [00:46<01:37,  1.57it/s]

tensor([0.4439, 0.4592, 0.0414], grad_fn=<AddBackward0>)


 34%|███████████████████████████▋                                                     | 79/231 [00:47<01:35,  1.59it/s]

tensor([0.5114, 0.4988, 0.0088], grad_fn=<AddBackward0>)


 35%|████████████████████████████                                                     | 80/231 [00:47<01:35,  1.59it/s]

tensor([0.4614, 0.5010, 0.0312], grad_fn=<AddBackward0>)


 35%|████████████████████████████▍                                                    | 81/231 [00:48<01:34,  1.59it/s]

tensor([0.4280, 0.4793, 0.0365], grad_fn=<AddBackward0>)


 35%|████████████████████████████▊                                                    | 82/231 [00:49<01:32,  1.62it/s]

tensor([0.4743, 0.5043, 0.0348], grad_fn=<AddBackward0>)


 36%|█████████████████████████████                                                    | 83/231 [00:49<01:31,  1.61it/s]

tensor([0.4202, 0.4592, 0.0100], grad_fn=<AddBackward0>)


 36%|█████████████████████████████▍                                                   | 84/231 [00:50<01:32,  1.59it/s]

tensor([0.4502, 0.4421, 0.0284], grad_fn=<AddBackward0>)


 37%|█████████████████████████████▊                                                   | 85/231 [00:51<01:34,  1.54it/s]

tensor([0.4199, 0.4535, 0.0106], grad_fn=<AddBackward0>)


 37%|██████████████████████████████▏                                                  | 86/231 [00:51<01:35,  1.51it/s]

tensor([0.4608, 0.5132, 0.0208], grad_fn=<AddBackward0>)


 38%|██████████████████████████████▌                                                  | 87/231 [00:52<01:38,  1.46it/s]

tensor([0.5376, 0.5096, 0.0419], grad_fn=<AddBackward0>)


 38%|██████████████████████████████▊                                                  | 88/231 [00:53<01:39,  1.43it/s]

tensor([0.4712, 0.5136, 0.0005], grad_fn=<AddBackward0>)


 39%|███████████████████████████████▏                                                 | 89/231 [00:53<01:42,  1.39it/s]

tensor([0.4288, 0.4573, 0.0131], grad_fn=<AddBackward0>)


 39%|███████████████████████████████▌                                                 | 90/231 [00:54<01:40,  1.40it/s]

tensor([ 0.5310,  0.5892, -0.0178], grad_fn=<AddBackward0>)


 39%|███████████████████████████████▉                                                 | 91/231 [00:55<01:37,  1.43it/s]

tensor([0.4699, 0.4887, 0.0143], grad_fn=<AddBackward0>)


 40%|████████████████████████████████▎                                                | 92/231 [00:55<01:33,  1.48it/s]

tensor([0.4855, 0.4539, 0.0068], grad_fn=<AddBackward0>)


 40%|████████████████████████████████▌                                                | 93/231 [00:56<01:32,  1.49it/s]

tensor([0.5514, 0.5617, 0.0149], grad_fn=<AddBackward0>)


 41%|████████████████████████████████▉                                                | 94/231 [00:57<01:29,  1.53it/s]

tensor([0.5108, 0.5167, 0.0160], grad_fn=<AddBackward0>)


 41%|█████████████████████████████████▎                                               | 95/231 [00:57<01:28,  1.54it/s]

tensor([0.5175, 0.4944, 0.0244], grad_fn=<AddBackward0>)


 42%|█████████████████████████████████▋                                               | 96/231 [00:58<01:32,  1.47it/s]

tensor([0.4903, 0.4616, 0.0333], grad_fn=<AddBackward0>)


 42%|██████████████████████████████████                                               | 97/231 [00:59<01:31,  1.46it/s]

tensor([0.4344, 0.4690, 0.0270], grad_fn=<AddBackward0>)


 42%|██████████████████████████████████▎                                              | 98/231 [01:00<01:31,  1.46it/s]

tensor([0.4558, 0.4781, 0.0061], grad_fn=<AddBackward0>)


 43%|██████████████████████████████████▋                                              | 99/231 [01:00<01:21,  1.63it/s]


KeyboardInterrupt: 

In [ ]:
correct = 0
total = 0
with torch.no_grad():
    for i in tqdm(range(len(test_x))):
        try:
            real_class = torch.argmax(test_y[i])
            net_out = net.forward(test_x[i].view(-1,1,50,50))
            
            predicted_class = torch.argmax(net_out)
 
            print(real_class,net_out)
            if predicted_class == real_class:
                correct += 1
            total += 1
            
        except Exception as e:
            print(str(e))
            break

print("Accuracy:",round(correct/total,3))


In [26]:
arr = torch.rand(4,5)

In [28]:
arr.size()[0]

4

In [30]:
arr[-2:]

tensor([[0.8750, 0.9578, 0.3404, 0.3153, 0.3000],
        [0.2464, 0.3774, 0.1818, 0.7264, 0.1102]])